### ISSUE TITLE
Consumption is computed using wrong wages

### ISSUE THREAD

**Issue by jose-moran** [KarlNaumann/Mark0#1]
It seems to me you are computing  Wtot using

https://github.com/KarlNaumann/Mark0/blob/2d8431248f02cc2a6cf68e30028ad8ad55b8d8f3/mark0_covid/mark0_covid.cpp#L390C21-L390C39

and then  setting the budget as

https://github.com/KarlNaumann/Mark0/blob/2d8431248f02cc2a6cf68e30028ad8ad55b8d8f3/mark0_covid/mark0_covid.cpp#L505

But presumably you want Wtot to be the sum of wages, not of wages times production.

**Comment by KarlNaumann** [comment]
No, this is correct: the household's income is wages * production (see e.g. profit of firms, they pay out W_i*Y_i).

Note that wages need to be adjusted for the amount worked (i.e. labor hours * hourly rate), which in Mark-0 is given by Y_i since we have unit labor productivity (one should probably divide by zeta to make sure, but it is generally set to 1.0 anyway). 
If this weren't the case - total wages paid would be insensitive to the state of unemployment, which is unintended.

**Comment by jose-moran** [comment]
Indeed, I was a bit confused by the variable name. Thanks!
